spring:
  application:
    name: EurekaServer2
    index: 2

server:
  port: 8762

eureka:
  instance:
    hostname: registry1
    port: 8761
    preferIpAddress: true
    metadataMap:
      instanceId: EUREKA${spring.application.index}_${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

logging:
  file: D:/Mes documents/tmp/logs/${spring.application.name}.log