spring:
  application:
    name: microservice1 
  zipkin:
    base-url: http://zipkin:9095/
  sleuth:
    sampler:
      percentage: 1.0 
      feign:
        enabled: false    

server:
  port: 8090

security:
  user:
    name: root
    password: password
  oauth2:
    resource:
      user-info-uri: http://${gateway.hostname}:${gateway.port}/uaa/user

gateway:
  hostname: gateway
  port: 8080

eureka:
  instance:
    hostname: registry1
    preferIpAddress: true
  client:
    eureka-server-port: 8761
    service-url.defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/,http://${eureka.backup.instance.hostname}:${eureka.backup.instance.port}/eureka/   
  backup: 
    instance:
      hostname: registry2
      port: 8762

logging:
  file: D:/Mes documents/tmp/logs/${spring.application.name}.log


