spring:
  application:
    name: ZuulProxyServer
  security:
    user:
      name: root
      password: password
      
server:
  port: 8083

zuul:
 trace-request-body: true
 routes:
   zuulserver:
     path: /ZuulServer/**
     url: http://{gateway.hostname}:{gateway.port}
     sensitive-headers:      

security:
    oauth2:
      client:
        client-id: acme
        client-secret: secret
        grant_type: password

logging:
  file: D:/Mes documents/tmp/logs/${spring.application.name}.log 