spring:
  application:
    name: ZuulProxyServer
      
server:
  port: 8083

zuul:
 trace-request-body: true
 routes:
   zuulserver:
     path: /ZuulServer/**
     url: http://${gateway.hostname}:${gateway.port}
     sensitive-headers:      

gateway:
  hostname: gateway
  port: 8082

security:
    oauth2:
      client:
        client-id: acme
        client-secret: secret
        grant_type: password

logging:
  file: D:/Mes documents/tmp/logs/${spring.application.name}.log 