FROM java:8-jre
RUN mkdir -p config && mkdir -p /home/arom/apps/app && mkdir -p /home/arom/apps/logs && mkdir -p /home/arom/apps/configRepo
VOLUME /home/arom/apps
ADD ./zipkin/lib/Zipkin-0.0.1-SNAPSHOT.jar /home/arom/apps/app/app.jar
EXPOSE 9095
COPY ./zipkin/config/application.properties /config/application.properties
RUN bash -c 'touch /home/arom/apps/app/app.jar'
ENTRYPOINT ["java","-jar","/home/arom/apps/app/app.jar"]
CMD "--spring.config.location=file:/config/"
