spring:
  application:
    name: zipkin
  cloud:
    config:
      uri: http://configserver:8888
server:
  port: 9095 

logging:
  file: D:/Mes documents/tmp/logs/${spring.application.name}.log
