cd ../annuaire
mvn package
cd ../hystrix
mvn package
cd ../microservice1
mvn package
cd ../microservice3  
mvn package
cd ../microservice5 
mvn package
cd ../authServer  
mvn package
cd ../configServer
mvn package
cd ../gateway 
mvn package
cd ../microservice2 
mvn package
cd ../microservice4
mvn package
cd ../microservice6
mvn package
cd ../reactMicroservice
mvn package
cd ../zipkin
mvn package
