FROM java:8-jre
RUN mkdir -p /home/arom/apps/app && mkdir -p /home/arom/apps/logs
RUN chown -R 1001:1001 /home/arom/apps/app /home/arom/apps/logs
RUN chmod -R 777 /home/arom/apps/app /home/arom/apps/logs
VOLUME /home/arom/apps
ENV JAR_FILE ./target/microservice6-0.0.1-SNAPSHOT.jar
ADD $JAR_FILE /home/arom/apps/app/app.jar
EXPOSE 8095
RUN bash -c 'touch /home/arom/apps/app/app.jar'
ENTRYPOINT ["java","-jar","/home/arom/apps/app/app.jar"]