spring:
  application:
    name: HystrixServer

server:
  port: 7080

turbine:
  appConfig: EurekaServer1,EurekaServer2,auth-server,ZuulServer,microservice1,microservice2,microservice3,microservice4
  cluster-name-expression: new String("default")

eureka:
  instance:
    hostname: registry1
    preferIpAddress: true
  client:
    eureka-server-port: 8761
    service-url: 
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/,http://${eureka.backup.instance.hostname}:${eureka.backup.instance.port}/eureka/   
  backup: 
    instance:
      hostname: registry2
      port: 8762

logging:
  file: /home/arom/apps/logs/${spring.application.name}.log
