spring:
  application:
    name: ZuulProxyServer
  security:
    user:
      name: root
      password: password
            
server:
  port: 8083

zuul:
 trace-request-body: true
 routes:
   zuulserver:
     path: /**
     url: http://gateway:8080
     sensitive-headers:      

gateway:
  hostname: gateway
  port: 8080

security:
    oauth2:
      client:
        client-id: acme
        client-secret: secret
        grant_type: password

logging:
  file: /home/arom/apps/logs/${spring.application.name}.log