FROM java:8-jre
RUN groupadd arom
RUN useradd arom -g arom
RUN mkdir -p config && mkdir -p /home/arom/apps/app && mkdir -p /home/arom/apps/logs 
ENV JAR_FILE ./target/configServer-0.0.1-SNAPSHOT.jar
ADD $JAR_FILE /home/arom/apps/app/app.jar
RUN chown -R arom:arom config /home/arom
RUN chmod -R 777 config /home/arom
USER arom
EXPOSE 8888
COPY ./src/main/resources/bootstrap-openshift.yml /config/application.yml
ENTRYPOINT ["java","-Dspring.profiles.active=openshift","-jar","/home/arom/apps/app/app.jar"]
CMD "--spring.config.location=file:/config/"