FROM java:8-jre
RUN mkdir -p config && mkdir -p /home/arom/apps/app && mkdir -p /home/arom/apps/logs && mkdir -p /home/arom/apps/configRepo
RUN chown -R 1001:1001 config /home/arom/apps/app /home/arom/apps/logs /home/arom/apps/configRepo
RUN chmod -R 777 config /home/arom/apps/app /home/arom/apps/logs /home/arom/apps/configRepo
VOLUME /home/arom/apps
ENV JAR_FILE ./target/configServer-0.0.1-SNAPSHOT.jar 
ADD $JAR_FILE /home/arom/apps/app/app.jar
USER 1001
EXPOSE 8888
COPY ./src/main/resources/application.properties /config/application.properties
RUN bash -c 'touch /home/arom/apps/app/app.jar'
ENTRYPOINT ["java","-jar","/home/arom/apps/app/app.jar"]
CMD "--spring.config.location=file:/config/"
