FROM java:8-jre
RUN mkdir -p /home/arom/apps/app && mkdir -p /home/arom/apps/logs
VOLUME /home/arom/apps
ADD ./monitoring/lib/hystrix-0.0.1-SNAPSHOT.jar /home/arom/apps/app/app.jar
EXPOSE 7080
RUN bash -c 'touch /home/arom/apps/app/app.jar'
ENTRYPOINT ["java","-jar","/home/arom/apps/app/app.jar"]
