FROM java:8-jre
RUN groupadd arom
RUN useradd arom -g arom
RUN mkdir -p /home/arom/apps/app && mkdir -p /home/arom/apps/logs 
ENV JAR_FILE ./target/gatewayProxy-0.0.1-SNAPSHOT.jar
ADD $JAR_FILE /home/arom/apps/app/app.jar
RUN chown -R arom:arom /home/arom
RUN chmod -R 777 /home/arom
USER arom
EXPOSE 8083
ENTRYPOINT ["java","-jar","/home/arom/apps/app/app.jar"] 
